### ISSUE TITLE
[provider] inventory service detects non-existing node

### ISSUE THREAD

**Issue by arno01** [akash-network/node#1403] opened 2021-10-07 09:34 UTC
Trying to help Chiroxo on Discord, his case is the following:

He's upgraded his akash provider from 0.12 to 0.14.0. (His initial deployment was done by the use of ansible playbook as per the official guide)

Now (not 100% sure whether he had the same issue before the upgrade), the inventory service reports 2 nodes whilst there is only 1.
Because of that, provider is not giving the bids thinking it's got **insufficient capacity**.

```
Oct 06 17:30:34 node1 start-provider.sh[103922]: E[2021-10-06|17:30:34.280] reserving resources                          module=bidengine-order order=akash1cduzr54kdle453lzt28nxnf99ed4tue8l97lvy/2950643/1/1 err="insufficient capacity"
```

## cmp=inventory-service nodes=2

```
# systemctl restart akash-provider
# journalctl --no-pager -u akash-provider --since '15 min ago' -l | grep -C5 'inventory fetched'

Oct 07 10:59:21 node1 systemd[1]: Started Akash Provider.
Oct 07 10:59:23 node1 start-provider.sh[1187056]: I[2021-10-07|10:59:23.450] using kube config file                       path=/root/.akash/k8s-admin.conf
Oct 07 10:59:27 node1 start-provider.sh[1187056]: I[2021-10-07|10:59:27.519] found leases                                 module=provider-cluster cmp=service num-active=0
Oct 07 10:59:27 node1 start-provider.sh[1187056]: I[2021-10-07|10:59:27.519] found deployments                            module=provider-cluster cmp=service num-active=0 num-skipped=6
Oct 07 10:59:27 node1 start-provider.sh[1187056]: D[2021-10-07|10:59:27.548] inventory ready                              module=provider-cluster cmp=service cmp=inventory-service
Oct 07 10:59:27 node1 start-provider.sh[1187056]: D[2021-10-07|10:59:27.548] inventory fetched                            module=provider-cluster cmp=service cmp=inventory-service nodes=2
Oct 07 10:59:27 node1 start-provider.sh[1187056]: D[2021-10-07|10:59:27.548] node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id=node1 available-cpu="units:<val:\"4750\" > attributes:<key:\"arch\" value:\"amd64\" > " available-memory="quantity:<val:\"15760183296\" > " available-storage="quantity:<val:\"377610551490\" > "
Oct 07 10:59:27 node1 start-provider.sh[1187056]: D[2021-10-07|10:59:27.548] node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id= available-cpu="units:<val:\"0\" > attributes:<key:\"arch\" > " available-memory="quantity:<val:\"0\" > " available-storage="quantity:<val:\"0\" > "
Oct 07 10:59:29 node1 start-provider.sh[1187056]: I[2021-10-07|10:59:29.850] found orders                                 module=bidengine-service count=85
Oct 07 10:59:29 node1 start-provider.sh[1187056]: D[2021-10-07|10:59:29.850] creating catchup order                       module=bidengine-service order=order/akash1057uu9jaehgqwk5g8g85nuq3esu0n2wxhejk9z/2200682/1/1
Oct 07 10:59:29 node1 start-provider.sh[1187056]: D[2021-10-07|10:59:29.850] creating catchup order                       module=bidengine-service order=order/akash109pttclfdj6erune0e8v9zed2pkvczq63u8yzp/2645453/1/1
```

## `node-id=<EMPTY>`

```
root@node1:/# journalctl -u akash-provider --since '10 hours ago' | grep 'node resources' | grep 'available-cpu' | tail -4
Oct 06 18:52:05 node1 start-provider.sh[103922]: D[2021-10-06|18:52:05.725] node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id=node1 available-cpu="units:<val:\"4750\" > attributes:<key:\"arch\" value:\"amd64\" > " available-memory="quantity:<val:\"15760183296\" > " available-storage="quantity:<val:\"377610551490\" > "
Oct 06 18:52:05 node1 start-provider.sh[103922]: D[2021-10-06|18:52:05.725] node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id= available-cpu="units:<val:\"0\" > attributes:<key:\"arch\" > " available-memory="quantity:<val:\"0\" > " available-storage="quantity:<val:\"0\" > "

Oct 06 18:52:56 node1 start-provider.sh[103922]: D[2021-10-06|18:52:56.204] node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id=node1 available-cpu="units:<val:\"4750\" > attributes:<key:\"arch\" value:\"amd64\" > " available-memory="quantity:<val:\"15760183296\" > " available-storage="quantity:<val:\"377610551490\" > "
Oct 06 18:52:56 node1 start-provider.sh[103922]: D[2021-10-06|18:52:56.205] node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id= available-cpu="units:<val:\"0\" > attributes:<key:\"arch\" > " available-memory="quantity:<val:\"0\" > " available-storage="quantity:<val:\"0\" > "
```

## kubectl get nodes -o wide
```
root@node1:/# kubectl get nodes -o wide
NAME    STATUS   ROLES                  AGE   VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
node1   Ready    control-plane,master   25d   v1.21.4   173.212.199.182   <none>        Ubuntu 21.04   5.11.0-37-generic   docker://20.10.8
root@node1:/#
```

## kubectl describe nodes

```
root@node1:/# kubectl describe nodes
Name:               node1
Roles:              control-plane,master
Labels:             akash.network/role=ingress
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=node1
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=
                    node-role.kubernetes.io/master=
                    node.kubernetes.io/exclude-from-external-load-balancers=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 173.212.199.182/32
                    projectcalico.org/IPv4IPIPTunnelAddr: 10.233.90.0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 11 Sep 2021 00:06:08 +0200
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  node1
  AcquireTime:     <unset>
  RenewTime:       Wed, 06 Oct 2021 20:08:22 +0200
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Wed, 06 Oct 2021 20:00:19 +0200   Wed, 06 Oct 2021 20:00:19 +0200   CalicoIsUp                   Calico is running on this node
  MemoryPressure       False   Wed, 06 Oct 2021 20:08:18 +0200   Sat, 11 Sep 2021 00:06:02 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Wed, 06 Oct 2021 20:08:18 +0200   Sat, 11 Sep 2021 00:06:02 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Wed, 06 Oct 2021 20:08:18 +0200   Sat, 11 Sep 2021 00:06:02 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Wed, 06 Oct 2021 20:08:18 +0200   Mon, 27 Sep 2021 16:34:29 +0200   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  173.212.199.182
  Hostname:    node1
Capacity:
  cpu:                6
  ephemeral-storage:  409733672Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             16388252Ki
  pods:               110
Allocatable:
  cpu:                5800m
  ephemeral-storage:  377610551490
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             15761564Ki
  pods:               110
System Info:
  Machine ID:                 e87a9702e3a4042c9f467004117bff0d
  System UUID:                9744e246-24e6-447f-9f7c-263582f3d14a
  Boot ID:                    f197b22a-c7f5-41d7-95aa-39765fb4428a
  Kernel Version:             5.11.0-37-generic
  OS Image:                   Ubuntu 21.04
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://20.10.8
  Kubelet Version:            v1.21.4
  Kube-Proxy Version:         v1.21.4
PodCIDR:                      10.233.64.0/24
PodCIDRs:                     10.233.64.0/24
Non-terminated Pods:          (11 in total)
  Namespace                   Name                                         CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                         ------------  ----------  ---------------  -------------  ---
  akash-services              akash-hostname-operator-858576b4f9-5qzq7     0 (0%)        0 (0%)      0 (0%)           0 (0%)         4h28m
  ingress-nginx               ingress-nginx-controller-6b4b785659-pq5mh    100m (1%)     0 (0%)      90Mi (0%)        0 (0%)         23h
  kube-system                 calico-kube-controllers-8575b76f66-dck5k     30m (0%)      100m (1%)   64M (0%)         256M (1%)      25d
  kube-system                 calico-node-vfbx8                            150m (2%)     300m (5%)   64M (0%)         500M (3%)      25d
  kube-system                 coredns-8474476ff8-xp8c2                     100m (1%)     0 (0%)      70Mi (0%)        170Mi (1%)     25d
  kube-system                 dns-autoscaler-7df78bfcfb-87l9w              20m (0%)      0 (0%)      10Mi (0%)        0 (0%)         25d
  kube-system                 kube-apiserver-node1                         250m (4%)     0 (0%)      0 (0%)           0 (0%)         25d
  kube-system                 kube-controller-manager-node1                200m (3%)     0 (0%)      0 (0%)           0 (0%)         25d
  kube-system                 kube-proxy-ltkm9                             0 (0%)        0 (0%)      0 (0%)           0 (0%)         25d
  kube-system                 kube-scheduler-node1                         100m (1%)     0 (0%)      0 (0%)           0 (0%)         25d
  kube-system                 nodelocaldns-v6vcd                           100m (1%)     0 (0%)      70Mi (0%)        170Mi (1%)     25d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests       Limits
  --------           --------       ------
  cpu                1050m (18%)    400m (6%)
  memory             370760Ki (2%)  1112515840 (6%)
  ephemeral-storage  0 (0%)         0 (0%)
  hugepages-1Gi      0 (0%)         0 (0%)
  hugepages-2Mi      0 (0%)         0 (0%)
Events:              <none>
```

**Comment by hydrogen18** [comment] 2021-10-15 12:05
I'll have to try & reproduce this in order to get to the bottom of it

**Comment by arno01** [comment] 2021-11-03 23:14
Update: He's redeployed his provider and he is now hitting this issue https://github.com/ovrclk/akash/issues/1439

**Comment by arno01** [comment] 2021-12-05 17:05
Chiroxo said he is not experiencing this issue anymore and he is good to close it.

**Comment by arno01** [comment] 2022-01-04 18:25
I think we should re-open this issue as I've just spotted it again on akash v0.14.1

https://github.com/ovrclk/akash/issues/1483#issue-1093638425

look for this line there:

```
Jan 04 12:08:23 foxtrot.provider start-provider.sh[349407]: D[2022-01-04|12:08:23.445] node resources                               module=provider-cluster cmp=service cmp=inventory-service node-id= available-cpu="units:<val:\"0\" > attributes:<key:\"arch\" > " available-memory="quantity:<val:\"0\" > " available-storage="quantity:<val:\"0\" > "
```

Provider's got these nodes:

```
cc @boz @dmikey

**Comment by andy108369** [comment] 2023-01-26 15:59
I haven't seen this issue ever since akash 0.16.x (mainnet3).
Closing.

**Closed by andy108369** 2023-01-26 15:59 UTC
